services:
  - type: web
    name: renomeador-nf-gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0