services:
  - type: web
    name: renomeador-backend-dev
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 10000
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    plan: free
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /

  - type: web
    name: gdm-frontend
    env: static
    rootDir: renomeador-nf-gdm-app
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://renomeador-backend-dev.onrender.com
  - type: web
    name: renomeador-backend-dev
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /
